name: Build and Package DEB

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake debhelper dh-make

      - name: Build project
        run: |
          mkdir build
          cd build
          cmake ..
          make

      - name: Create DEB package
        run: |
          mkdir -p debian/source
          echo "3.0 (native)" > debian/source/format
          dh_make --createorig --single --yes
          dpkg-buildpackage -us -uc

      - name: Upload DEB artifact
        uses: actions/upload-artifact@v3
        with:
          name: androidtools-qml-deb
          path: ../*.deb